name: Pull Request Check 
on: 
  workflow_dispatch:
  pull_request: 
    branches: 
      - master 
jobs: 
  display-removed-text:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get removed text
      run: |
        REMOVED_TEXT=$(git diff --color=always ${{ github.event.pull_request.base.ref }}...${{ github.event.pull_request.head.ref }} | grep -E "^-[^-]" | cut -c2- | sed -E "s/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[mGK]//g" | sed "s/^/    /")
        if [ -n "$REMOVED_TEXT" ]; then
          echo "Removed text:"
          echo "$REMOVED_TEXT"
          exit 1
        fi
