name: Pull Request Check 
on: 
  workflow_dispatch:
  pull_request: 
    branches: 
      - master 
jobs: 
  check-diff: 
    name: Check diff between base and head branches 
    runs-on: ubuntu-latest 
    steps: 
    - uses: actions/checkout@v2 
      with:
          ref: ${{ github.event.pull_request.head.ref }}
    - name: Check diff 
      run: | 
        if git diff --quiet "${{ github.event.pull_request.base.ref }}...${{ github.event.pull_request.head.ref }}" && | grep "automationId"; then 
          echo "No differences found between base and head branches, and no files with 'automationId' found." 
          exit 0 
        else 
          echo "Differences found between base and head branches, or files with 'automationId' found." 
          exit 1 
        fi 

 
