name: Pull Request Check 
on: 
  pull_request: 
    branches: 
      - master 
jobs: 
  check-diff: 
    name: Check diff between base and head branches 
    runs-on: ubuntu-latest 
    steps: 
    - uses: actions/checkout@v3
    - name: Check diff
      run: |
        # Get the differences between base(master) and head(PR branch) branches
        git fetch origin ${{ github.event.pull_request.base.ref }}
        git fetch origin ${{ github.event.pull_request.head.ref }}
        echo "starting"
        echo $(git status)
        
        echo $(git checkout ${{ github.event.pull_request.head.ref }})
        
        DIFF=$(git diff ${{ github.event.pull_request.head.ref }} ${{ github.event.pull_request.base.ref }})
        echo $DIFF
        
        # Check if 'automationId' is removed
        #if echo "$DIFF" | grep -q "automationId"; then
        #  echo "No differences found between base and head branches, or 'automationId' text is removed."
        #  exit 1
        #else
        #  echo "Differences found between base and head branches, and 'automationId' text is not removed."
        # exit 0
        #fi

 
