name: Pull Request Check 
on: 
  workflow_dispatch:
  pull_request: 
    branches: 
      - master 
jobs: 
  check-diff: 
    name: Check diff between base and head branches 
    runs-on: ubuntu-latest 
    steps: 
    - uses: actions/checkout@v3
    - name: Check diff
      run: |
        # Get the differences between base and head branches
          git diff --name-only ${{ github.event.pull_request.base.ref }}...${{ github.event.pull_request.head.ref }} | xargs grep -L "automationId" || { echo "ERROR: 'automationId' text removed" && exit 1; }

        
 
