name: Pull Request Check 
on: 
  workflow_dispatch:
  pull_request: 
    branches: 
      - master 
jobs: 
  check-diff: 
    name: Check diff between base and head branches 
    runs-on: ubuntu-latest 
    steps: 
    - uses: actions/checkout@v1 
    - name: Check diff
      run: |
        # Get the differences between base and head branches
        DIFF=$(git diff --name-only origin/master HEAD)
        
        # Check if 'automationId' is removed
        if echo "$DIFF" | grep -q "automationId"; then
          echo "No differences found between base and head branches, or 'automationId' text is removed."
          echo "$DIFF"
          echo "$DIFF" | grep -q "automationId"
          exit 1
        else
          echo "Differences found between base and head branches, and 'automationId' text is not removed."
          echo "$DIFF"
          echo "$DIFF" | grep -q "automationId"
          exit 0
        fi

 
