name: Pull Request Check 
on: 
  pull_request: 
    branches: 
      - master 
jobs: 
  check-diff: 
    name: Check diff between base and head branches 
    runs-on: ubuntu-latest 
    steps: 
    - uses: actions/checkout@v3
    - name: Check diff
      run: |
        # check if the PR has any automationIds deleted 
        # github.event.pull_request.head.ref is PR branch
        # github.event.pull_request.base.ref is master branch
        
        echo $(git fetch origin ${{ github.event.pull_request.head.ref }})
        echo $(git fetch origin ${{ github.event.pull_request.base.ref }})
        echo $(git status)
        echo $(git checkout ${{ github.event.pull_request.head.ref }})
        
        echo $(git diff origin/${{github.event.pull_request.base.ref}} ${{github.event.pull_request.head.ref}} -U0 --word-diff-regex='[^[:space:]]+' )
        echo 'actual commandS to get removed'
        
        # old
        # echo $(git diff origin/${{github.event.pull_request.base.ref}} ${{github.event.pull_request.head.ref}} --word-diff-regex='/automationId|data-automation-id/g' | grep -E '\[-automationId')
        
        AUTOMATION_ID_REMOVED=$(git diff origin/${{github.event.pull_request.base.ref}} ${{github.event.pull_request.head.ref}} -U0 --word-diff-regex='[^[:space:]]+'  | grep -E '\[-automationId')
        echo $AUTOMATION_ID_REMOVED
        
        # old
        # DATA_AUTOMATION_ID_REMOVED=$(git diff origin/${{github.event.pull_request.base.ref}} ${{github.event.pull_request.head.ref}} --word-diff-regex='/automationId|data-automation-id/g' | grep -E '\[-data-automation-id')
        
        echo $(git diff origin/${{github.event.pull_request.base.ref}} ${{github.event.pull_request.head.ref}} -U0 --word-diff-regex='[^[:space:]]+' | grep -E '\[-data-automation-id')
        # DATA_AUTOMATION_ID_REMOVED=$(git diff origin/${{github.event.pull_request.base.ref}} ${{github.event.pull_request.head.ref}} -U0 --word-diff-regex='[^[:space:]]+' | grep -E '\[-data-automation-id')
        echo $DATA_AUTOMATION_ID_REMOVED
        
        if echo "$AUTOMATION_ID_REMOVED | grep -E '\[-automationId'"; then
          echo "'automationId' text is removed."
          exit 1
        else
          echo "'automationId' text is not removed."
          exit 0
        fi
