name: Pull Request Check 
on: 
  pull_request: 
    branches: 
      - master 
jobs: 
  check-diff: 
    name: Check diff between base and head branches 
    runs-on: ubuntu-latest 
    steps: 
    - uses: actions/checkout@v3
    - name: Check diff
      run: |
        # check if the PR has any automationIds deleted 
        # github.event.pull_request.head.ref is PR branch
        # github.event.pull_request.base.ref is master branch
        
        echo $(git fetch origin ${{ github.event.pull_request.head.ref }})
        echo $(git fetch origin ${{ github.event.pull_request.base.ref }})
        echo $(git status)
        echo $(git checkout ${{ github.event.pull_request.head.ref }})
        
        echo $(git diff ${{github.event.pull_request.head.ref}} origin/${{github.event.pull_request.base.ref}} --unified=0 --word-diff-regex='[^[:space:]]')
        echo 'actual command to get removed'
        
        REMOVED=$(git diff ${{github.event.pull_request.head.ref}} origin/${{github.event.pull_request.base.ref}} --unified=0 --word-diff-regex='[^[:space:]]' | grep -E '\[-automationId')
        #REMOVED=$(git diff ${{github.event.pull_request.head.ref}} origin/${{github.event.pull_request.base.ref}} --word-diff-regex='[^[:space:]]+')
        echo $REMOVED
        
        #also need to see if just the text automationId is removed from a line which is not deleted
        
        # if 'automationId' is in removed words
        if echo "$REMOVED" | grep -q "automationId"; then
          echo "'automationId' text is removed."
          exit 1
        else
          echo "'automationId' text is not removed."
         exit 0
        fi

 
